### ISSUE TITLE
Exception thrown trying to use parser generated by 0.4.14

### ISSUE THREAD

**Issue by markwatkinson** [zaach/jison#246]
I'm using Jison 0.4.14 to try to generate a parser for [this grammar](https://github.com/markwatkinson/loljs/blob/18fee35f3f478cbd38bc50cdfec56db30e526e02/src/loljs.jison), which is created using [this script](https://github.com/markwatkinson/loljs/blob/18fee35f3f478cbd38bc50cdfec56db30e526e02/src/generate.js). The parser is generated, but warns of two conflicts (which I don't think should affect this, but I may be wrong).

Then trying to use it in a Node (v0.10.25) REPL, I'm getting:
```
> var p = require('./parser.js').parser
undefined
> p
{ yy: {} }
> p.parse("1")
TypeError: Object prototype may only be an Object or null
    at Function.create (native)
    at Object.parse (/home/mark/projects/loljs/parser.js:312:24)
    at repl:1:4
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
    at Interface.EventEmitter.emit (events.js:95:17)
    at Interface._onLine (readline.js:202:10)
    at Interface._line (readline.js:531:8)
    at Interface._ttyWrite (readline.js:760:14)
    at ReadStream.onkeypress (readline.js:99:10)
```

The line it's referencing (parser.js:312) is 
```javascript
var lexer = Object.create(this.lexer);
```

and `this.lexer` is undefined. I can't see any other reference to `this.lexer` anywhere in the file.

Here's the generated parser: https://gist.github.com/markwatkinson/c211a15e08d43c71e447

0.4.15 hits the same problem.
0.4.13 seems to work ok

**Comment by flipchart** [comment]
Same problem on 0.4.15 as well. Using module-deps and browser-pack (components of browserify) to do custom bundling, but not entirely sure that's the cause

**Comment by nolanlawson** [comment]
Ran into this myself today. I can try to find a fix. Unless someone else has already fixed it, and it's just hanging out in a fork somewhere?

**Comment by nolanlawson** [comment]
OK, I found a fix.

**Comment by Blackhol3** [comment]
I still have the same problem.

**Comment by mezzario** [comment]
me as well, 0.4.15

**Comment by Blackhol3** [comment]
@mezzario I've discovered the problem was, at least for me, that no lexer is included by default. I've personally written a simple one myself, as described [in the documentation](http://zaach.github.io/jison/docs/#custom-scanners), but I guess you can also simply add the following code at the beginning of your grammar file:

    %lex
    %%
    /lex

**Comment by pietersv** [comment]
Is there a way to run the examples?  Am a newbie gettig started with jison.  If I try an example that doesn't have a lexer defined, I get the same error message  when trying to use the `examples/ansic.jison` (with either  npm 0.4.15 or this GitHub repo):

```js
var fs = require("fs");
var jison = require("..");

var bnf = fs.readFileSync(__dirname + "/ansic.jison", "utf8");
var parser = new jison.Parser(bnf);

parser.parse('void main() {}')
``` 

which yields this message:
```
TypeError: Object prototype may only be an Object or null: undefined
    at Function.create (native)
    at Object.parse (eval at createParser (/Users/me/Exp/jison/lib/jison.js:1327:23), <anonymous>:33:24)
    at Object.<anonymous> (/Users/me/Exp/jison/examples/myparser.js:8:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

Running it from the command line yields the same error message:
```sh
jison ansic.jison 
echo "void main() {}" > ansic.txt
node ansic.js ansic.txt 
```


Adding a null lexer didn't seem to work:
```
%lex
%%

/lex
``` 
at the top of `ansic.jison` causes a new error message:
```
Error: Parse error on line 2:
%%
--^
Expecting 'ACTION', '{', '<', '|', '(', 'SPECIAL_GROUP', '/', '/!', '.', '^', '$', 'NAME_BRACE', 'ANY_GROUP_REGEX', 'ESCAPE_CHAR', 'STRING_LIT', 'CHARACTER_LIT', got 'EOF'
    at Object.parseError (/Users/me/Exp/jison/node_modules/lex-parser/lex-parser.js:217:15)
    at Object.parse (/Users/me/Exp/jison/node_modules/lex-parser/lex-parser.js:274:22)
    at Object.exports.parse (/Users/me/Exp/jison/node_modules/lex-parser/lex-parser.js:839:48)
    at parseLex (/Users/me/Exp/jison/node_modules/ebnf-parser/ebnf-parser.js:39:21)
    at Object.bnf.yy.addDeclaration (/Users/me/Exp/jison/node_modules/ebnf-parser/ebnf-parser.js:14:23)
    at Object.anonymous (/Users/me/Exp/jison/node_modules/ebnf-parser/parser.js:96:30)
    at Object.parse (/Users/me/Exp/jison/node_modules/ebnf-parser/parser.js:315:36)
    at Object.parse (/Users/me/Exp/jison/node_modules/ebnf-parser/ebnf-parser.js:5:55)
    at Jison_Generator [as constructor] (/Users/me/Exp/jison/lib/jison.js:83:30)
    at (anonymous function) [as constructor] (/Users/me/Exp/jison/lib/util/typal.js:23:28)
```

So I tried adding a new lexing rule I think won't conflict 
```
%lex
%%
"PI"                  return 'PI';

/lex
``` 
and that generated a new message:
```
undefined:27
        throw new _parseError(str, hash);
        ^
Error
    at Object.parseError (eval at createParser (/Users/me/Exp/jison/lib/jison.js:1327:23), <anonymous>:25:33)
    at Object.parseError (eval at RegExpLexer (/Users/me/Exp/jison/node_modules/jison-lex/regexp-lexer.js:124:22), <anonymous>:7:28)
    at Object.next (eval at RegExpLexer (/Users/me/Exp/jison/node_modules/jison-lex/regexp-lexer.js:124:22), <anonymous>:262:25)
    at Object.lex (eval at RegExpLexer (/Users/me/Exp/jison/node_modules/jison-lex/regexp-lexer.js:124:22), <anonymous>:272:22)
    at lex (eval at createParser (/Users/me/Exp/jison/lib/jison.js:1327:23), <anonymous>:62:27)
    at Object.parse (eval at createParser (/Users/me/Exp/jison/lib/jison.js:1327:23), <anonymous>:75:26)
    at Object.<anonymous> (/Users/me/Exp/jison/examples/myparser.js:8:8)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
```

Interestingly that last message is a parse error.   Is this parser actually working but `void main() {}` isn't valid C?   I tried `int a` etc. to no avail.

Examples that define a lexer are fine.  So `basic2.jison` fails but `basic2_lex.jison` runs fine.

Running `npm test` seems to return fine.

**Comment by cosmicexplorer** [comment]
Pretty much all the documentation [here](https://zaach.github.io/jison/docs/#using-the-generated-parser) implied that we should use (snipped from docs):
``` javascript
var parser = require("./calculator").parser;
console.log(parser.parse("4 * 5")); // => TypeError
```
where `./calculator.js` is the exported javascript output from jison for the calculator grammar described in the docs. This is wrong and was causing the error message shown in this thread. Instead, just calling `.parse` works:
``` javascript
var parse = require("./calculator").parse;
console.log(parse("4 * 5")); // => 20
```

I don't know why this works (didn't spend too much time looking into it), but it probably has something to do with the definition
``` javascript
exports.parse = function () { return parser.parse.apply(parser, arguments); };
```
at the bottom of the generated file, and the difference from parser.parse (maybe `.parse()` isn't part of `parser`'s prototype? idk).

**Comment by gentwo** [comment]
The problem seems to be that when the parser is generated using code, the lexer does not get generated. Not sure if this is by design.

To elaborate:
```
jison.Parser.generate
```

Doesn't appear to generate the lexer at all, even though the rules are there in the grammar file.
Hence lexer is undefined. The following lines
```
/* generated by jison-lex 0.3.4 */
var lexer = (function(){
[...]
return lexer;
})();
parser.lexer = lexer;
```
simply don't exist in the generated parser.

Using the command line, it seems to work fine. i.e.,
```
$ jison grammar.jison
```
Does generate the lexer. 

Both methods of accessing the parser. ie
```
var parser = require("./calculator").parser;
console.log(parser.parse("4 * 5")); // => TypeError
```
and

```
var parse = require("./calculator").parse;
console.log(parse("4 * 5")); // => 20
```
works for me when using the parser generated from the command line.

**Comment by cosmicexplorer** [comment]
That's weird, both seem to work now. Not sure what silly thing I was doing then.

**Comment by gentwo** [comment]
Any idea what I'm doing wrong that's causing the lexer to not be generated? Do I need to pass some additional options? I am calling it like this:
```
var fs = require("fs");
var jison = require("jison");

var grammar = fs.readFileSync("grammar.jison", "utf8");
var parser = new jison.Parser(grammar);

// generate source, ready to be written to disk
var parserSource = parser.generate({moduleName: "myParser"});
```

**Comment by yosbelms** [comment]
@gentwo I'm generating with the following code:
```js
    var
    fs      = require('fs'),
    bnf     = require('jison/node_modules/ebnf-parser'),
    lex     = require('jison/node_modules/lex-parser'),
    grammar = bnf.parse(fs.readFileSync('./src/bnf/cor.y', 'utf8')),
    lexer   = lex.parse(fs.readFileSync('./src/bnf/cor.l', 'utf8'));

    grammar.lex = lexer;
    gen         = new jison.Generator(grammar, opts);
    parserSrc   = gen.generate(opts);

    fs.writeFileSync('./src/parser.js', parserSrc);
```

you can find the complete source code in https://github.com/yosbelms/cor/blob/master/make starting from line 102

**Comment by gentwo** [comment]
@yosbelms Awesome! Thanks! That's exactly what I was looking for. This means I need to separate my grammar and lexing rules :-(

Also, is this the expected use or is this a bug?

**Comment by mbroadst** [comment]
I'm experiencing the same problem when trying to generate from the provided [ansic.jison](https://github.com/zaach/jison/blob/master/examples/ansic.jison). 

initial steps:
```
$ npm install jison
$ wget https://raw.githubusercontent.com/zaach/jison/master/examples/ansic.jison
$ ./node_modules/.bin/jison ansic.jison
```

this results in `ansic.js` being created, at which point a cursory attempt to use it to parse a c file seems to file with the same error:
```
mbroadst@retinoid:jison-test$ node ansic.js test.c
/Users/mbroadst/jison-test/ansic.js:106
    var lexer = Object.create(this.lexer);
                       ^

TypeError: Object prototype may only be an Object or null: undefined
    at Object.parse (/Users/mbroadst/jison-test/ansic.js:106:24)
    at Object.commonjsMain [as main] (/Users/mbroadst/jison-test/ansic.js:259:27)
    at Object.<anonymous> (/Users/mbroadst/jison-test/ansic.js:262:11)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
```

This is using version 0.4.17, am I doing this incorrectly? The docs seems to indicate I should at very least be able to do what I'm doing to verify the generation occurred properly.

**Comment by Blackhol3** [comment]
@mbroadst There is no lexer in your `.jison` file. You should either add [the corresponding section](http://zaa.ch/jison/docs/#the-concepts-of-jison) at its beginning, or create a [custom scanner](http://zaa.ch/jison/docs/#custom-scanners).

**Comment by mbroadst** [comment]
@Blackhol3 Yeah I realized the err of my ways shortly after writing the comment, and therefore deleted it.  Do you happen to know of an existing ansi c lexer written for jison? I'm going through an existing lex spec for it, but I'm sure I'll screw it up the first time here :)

**Comment by Blackhol3** [comment]
@mbroadst No, I don't know any, sorry. But lexers can generally be relatively easily written by yourself, if necessary :-).

**Comment by pietersv** [comment]
https://docs.omniref.com/js/npm/jison/0.2.11/files/tests/grammar/lex/ansic.jisonlex

**Comment by mbroadst** [comment]
@pietersv just when I finished my own :) thanks for the resource!

**Comment by irwansyahwii** [comment]
Still happening on 0.4.14 and above also some versions below. Why someone closed the issue since I can't see any working solution from the above proposed solutions

**Comment by cosmicexplorer** [comment]
How are you generating the parser and what is the error message?

**Comment by irwansyahwii** [comment]
@cosmicexplorer I generated the parser using this:

`
$ jison grammar.jison
`

And I got lexer undefined error message. I tried using the JavaScriptCore grammar from the examples

**Comment by Blackhol3** [comment]
@irwansyahwii The root of problem is stated clearly in numerous messages of this thread: you should define a lexer, either inside your `.jison` file, or with [a custom scanner](http://zaa.ch/jison/docs/#custom-scanners).
