### ISSUE TITLE
Not work for JSON format

### ISSUE THREAD

**Issue by xndcn** [zaach/jison#276]
When input file is raw JSON format, it produces error:

> /usr/local/lib/node_modules/jison/lib/cli.js:142
>    var settings = grammar.options || {};
>                          ^
> TypeError: Cannot read property 'options' of undefined
>    at Object.generateParserString (/usr/local/lib/node_modules/jison/lib/cli.js:142:27)
>    at processGrammar (/usr/local/lib/node_modules/jison/lib/cli.js:74:22)
>    at processInputFile (/usr/local/lib/node_modules/jison/lib/cli.js:106:22)
>    at Object.cliMain [as main](/usr/local/lib/node_modules/jison/lib/cli.js:131:9)
>    at Object.<anonymous> (/usr/local/lib/node_modules/jison/lib/cli.js:185:9)
>    at Module._compile (module.js:456:26)
>    at Object.Module._extensions..js (module.js:474:10)
>    at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:312:12)
>    at Function.Module.runMain (module.js:497:10)

**Comment by gaye** [comment]
I think this was a regression introduced after `0.4.13`
