### ISSUE TITLE
jison-lex borked

### ISSUE THREAD

**Issue by gaye** [zaach/jison#287]
/home/gareth/Documents/math/.tup/mnt/@tupjob-54872/home/gareth/Documents/math/node_modules/jison/node_modules/jison-lex/regexp-lexer.js:54
            m = new RegExp("^(?:"+m+")", caseless ? 'i':'');
                                                        ^
SyntaxError: Invalid regular expression: /^(?:()/: Unterminated group
    at new RegExp (native)
    at prepareRules (/home/gareth/Documents/math/.tup/mnt/@tupjob-54872/home/gareth/Documents/math/node_modules/jison/node_modules/jison-lex/regexp-lexer.js:54:57)
    at Object.buildActions (/home/gareth/Documents/math/.tup/mnt/@tupjob-54872/home/gareth/Documents/math/node_modules/jison/node_modules/jison-lex/regexp-lexer.js:113:18)
    at Object.RegExpLexer (/home/gareth/Documents/math/.tup/mnt/@tupjob-54872/home/gareth/Documents/math/node_modules/jison/node_modules/jison-lex/regexp-lexer.js:139:39)
    at Jison_Generator (/home/gareth/Documents/math/.tup/mnt/@tupjob-54872/home/gareth/Documents/math/node_modules/jison/lib/jison.js:111:22)
    at (anonymous function) (/home/gareth/Documents/math/.tup/mnt/@tupjob-54872/home/gareth/Documents/math/node_modules/jison/lib/util/typal.js:23:28)
    at new o.constructor (/home/gareth/Documents/math/.tup/mnt/@tupjob-54872/home/gareth/Documents/math/node_modules/jison/lib/util/typal.js:77:70)
    at new Jison_Generator (/home/gareth/Documents/math/.tup/mnt/@tupjob-54872/home/gareth/Documents/math/node_modules/jison/lib/jison.js:1740:20)
    at processGrammar (/home/gareth/Documents/math/.tup/mnt/@tupjob-54872/home/gareth/Documents/math/node_modules/jison/lib/cli.js:114:21)
    at Object.exports.main (/home/gareth/Documents/math/.tup/mnt/@tupjob-54872/home/gareth/Documents/math/node_modules/jison/lib/cli.js:75:56)

**Comment by gaye** [comment]
Version of jison is 0.4.13 and version of jison-lex is 0.2.x. jison-lex gets upgraded in jison 0.4.14, but I can't use because of https://github.com/zaach/jison/issues/276

**Comment by gaye** [comment]
Actually I forgot to escape a parens. My bad!
